Setup CI (#1)
* trigger

* fix flake8 errors

* fix

* use flit

* add stub test

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -28,7 +28,7 @@ jobs:
       targetType: inline
       script: |
         python -m pip install -U pip setuptools wheel
-        pip install black flake8 pytest
+        pip install black flake8 pytest flit
   - task: Bash@3
     displayName: Lint (black)
     inputs:
@@ -41,40 +41,39 @@ jobs:
       targetType: inline
       script: |
         flake8
-  - task: Bash@3
-    displayName: Build wheel and install in development mode
-    inputs:
-      targetType: inline
-      script: |
-        python setup.py develop
-        python setup.py bdist_wheel
-  - task: Bash@3
-    displayName: Test
-    inputs:
-      targetType: inline
-      script: |
-        pytest --disable-warnings --junit-xml=results.xml || true
-
-        # Fail the task if results.xml was not created
-        if [[ ! -f results.xml ]]
-        then
-          echo "##vso[task.logissue type=error]No test results were found"
-          exit 1
-        fi
-  - task: PublishTestResults@2
-    inputs:
-      testResultsFiles: results.xml
-      mergeTestResults: true
-      failTaskOnFailedTests: true
-      testRunTitle: Test $(vmImage)
+  # - task: Bash@3
+  #   displayName: Build wheel and install in development mode
+  #   inputs:
+  #     targetType: inline
+  #     script: |
+  #       python setup.py develop
+  #       python setup.py bdist_wheel
+  # - task: Bash@3
+  #   displayName: Test
+  #   inputs:
+  #     targetType: inline
+  #     script: |
+  #       pytest --disable-warnings --junit-xml=results.xml || true
+  #
+  #       # Fail the task if results.xml was not created
+  #       if [[ ! -f results.xml ]]
+  #       then
+  #         echo "##vso[task.logissue type=error]No test results were found"
+  #         exit 1
+  #       fi
+  # - task: PublishTestResults@2
+  #   inputs:
+  #     testResultsFiles: results.xml
+  #     mergeTestResults: true
+  #     failTaskOnFailedTests: true
+  #     testRunTitle: Test $(vmImage)
   - task: Bash@3
     displayName: Test (packaged)
     inputs:
       targetType: inline
       script: |
-        python setup.py develop --uninstall
-        rm -rf ./wgpu ./build ./egg-info
-        pip install dist/*.whl
+        flit install
+        rm -rf ./spirv ./build ./egg-info
         pytest --disable-warnings --junit-xml=results-packaged.xml || true
 
         # Fail the task if results-packaged.xml was not created
@@ -89,3 +88,4 @@ jobs:
       mergeTestResults: true
       failTaskOnFailedTests: true
       testRunTitle: Test $(vmImage) (packaged)
+
